#===================================================================================#
# Site Information
#===================================================================================#
site_name: AWSM.ID
repo_name: "muhx/awsm"
repo_url: https://github.com/muhx/awsm
site_url: https://awsm.id/
site_description: >-
  Everything AWSM in one place, inspired by awesome project at GitHub
site_author: muhx
copyright: Copyright &copy; 2022 <a href="https://awsm.id">AWSM.ID</a>
dev_addr: !ENV [DEV_ADDR, '0.0.0.0:8080']

#===================================================================================#
# Mkdocs Theme (Material Mkdocs) + Extras
#===================================================================================#
theme:
  name: material
  custom_dir: material
  language: en
  icon:
    logo: logo
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  favicon: assets/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - header.autohide
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - announce.dismiss
  palette: # https://www.materialpalette.com/colors
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: yellow
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  include_sidebar: true

extra:
  social:
    - icon: material/home
      link: 'https://awsm.id'
    - icon: material/github
      link: 'https://github.com/muhx/awsm'
  alternate:
    - name: Bahasa
      link: /id
      lang: id
    - name: English
      link: /
      lang: en
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_KEY, 'RandomKey']
    feedback:
      title: Apakah halaman ini berguna?
      ratings:
        - icon: material/heart
          name: Sangat berguna
          data: 1
          note: >-
            Terima kasih feedbacknya!
        - icon: material/heart-broken
          name: Berguna
          data: 0
          note: >- 
            Kita capek lho ngetiknya!
  generator: false

extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/feedback.js


plugins:
  - social
  - tags:
      tags_file: tags.md
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: " ¶"
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem

#===================================================================================#
# Mkdocs Navigation Tree
#===================================================================================#
nav:
  - Home:
    - "index.md"
    - "about.md"
  - Platform:
    - Node.js:
      - "platform/nodejs/nodejs-overview.md"
      - Packages:
        - Mad Science:
          - "platform/nodejs/packages/mad-science/webtorrent.md"
  - "tags.md"
