name: publish

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-rc'
      - '!v*.*.*-dev'

env:
  PYTHON_VERSION: 3.x

jobs:
  publish:
    name: build and push docker image
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lowercase repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Get Tag
        run: echo "TAG=${GITHUB_REF:10}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/${{ env.REPOSITORY_NAME }}:latest
            ghcr.io/${{ env.REPOSITORY_NAME }}:${{ env.TAG }}

      - name: Publish Docker image
        run: |
          docker push --all-tags ghcr.io/${{ env.REPOSITORY_NAME }}